fix(core): SQLITE_ERROR: table mastra_evals has no column named createdAt (#2817)
In https://github.com/mastra-ai/mastra/pull/2754 we accidentally broke
evals insertion. This should fix it by not referencing any specific
column names when serializing dates before insertion

```
LibsqlError: SQLITE_ERROR: table mastra_evals has no column n
amed createdAt
    at mapSqliteError (file:///Users/tylerbarnes/code/throwaw
```